name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/browser-use/browser-use.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
