name: test

on:
  push:
    branches:
      - main
      - stable
      - 'releases/**'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    
jobs:
  tests:
    name: ${{matrix.test}} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
        - browser/patchright
        - browser/user_binary
        - browser/remote_cdp
        - models/openai
        - models/google
        - models/anthropic
        - models/azure
        - models/deepseek
        - models/grok
        - functionality/click
        - functionality/tabs
        - functionality/input
        - functionality/scroll
        - functionality/upload
        - functionality/download
        - functionality/save
        - functionality/vision
        - functionality/memory
        - functionality/planner
        - functionality/hooks
        
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run --with=dotenv pytest tests/${{ matrix.test }}.py || true
